export type Corpses =
  | "Imperfect Hydra"
  | "Hydra"
  | "Perfect Hydra"
  | "Imperfect Frozen Cannibal"
  | "Frozen Cannibal"
  | "Perfect Frozen Cannibal"
  | "Imperfect Fiery Cannibal"
  | "Fiery Cannibal"
  | "Perfect Fiery Cannibal"
  | "Imperfect Dark Marionette"
  | "Dark Marionette"
  | "Perfect Dark Marionette"
  | "Imperfect Naval Officer"
  | "Naval Officer"
  | "Perfect Naval Officer"
  | "Imperfect Dancing Sword"
  | "Dancing Sword"
  | "Perfect Dancing Sword"
  | "Imperfect Needle Horror"
  | "Needle Horror"
  | "Perfect Needle Horror"
  | "Imperfect Serpent Warrior"
  | "Serpent Warrior"
  | "Perfect Serpent Warrior"
  | "Imperfect Pain Artist"
  | "Pain Artist"
  | "Perfect Pain Artist"
  | "Imperfect Sawblade Horror"
  | "Sawblade Horror"
  | "Perfect Sawblade Horror"
  | "Imperfect Blood Demon"
  | "Blood Demon"
  | "Perfect Blood Demon"
  | "Imperfect Slashing Horror"
  | "Slashing Horror"
  | "Perfect Slashing Horror"
  | "Imperfect Druidic Alchemist"
  | "Druidic Alchemist"
  | "Perfect Druidic Alchemist"
  | "Imperfect Blasphemer"
  | "Blasphemer"
  | "Perfect Blasphemer"
  | "Imperfect Judgemental Spirit"
  | "Judgemental Spirit"
  | "Perfect Judgemental Spirit"
  | "Imperfect Primal Thunderbird"
  | "Primal Thunderbird"
  | "Perfect Primal Thunderbird"
  | "Imperfect Spirit of Fortune"
  | "Spirit of Fortune"
  | "Perfect Spirit of Fortune"
  | "Imperfect Primal Demiurge"
  | "Primal Demiurge"
  | "Perfect Primal Demiurge"
  | "Imperfect Runic Skeleton"
  | "Runic Skeleton"
  | "Perfect Runic Skeleton"
  | "Imperfect Warlord"
  | "Warlord"
  | "Perfect Warlord"
  | "Imperfect Dark Reaper"
  | "Dark Reaper"
  | "Perfect Dark Reaper"
  | "Imperfect Hulking Miscreation"
  | "Hulking Miscreation"
  | "Perfect Hulking Miscreation"
  | "Imperfect Sanguimancer Demon"
  | "Sanguimancer Demon"
  | "Perfect Sanguimancer Demon"
  | "Imperfect Spider Matriarch"
  | "Spider Matriarch"
  | "Perfect Spider Matriarch"
  | "Imperfect Half-remembered Goliath"
  | "Half-remembered Goliath"
  | "Perfect Half-remembered Goliath"
  | "Imperfect Meatsack"
  | "Meatsack"
  | "Perfect Meatsack"
  | "Imperfect Eldritch Eye"
  | "Eldritch Eye"
  | "Perfect Eldritch Eye"
  | "Imperfect Forest Tiger"
  | "Forest Tiger"
  | "Perfect Forest Tiger"
  | "Imperfect Guardian Turtle"
  | "Guardian Turtle"
  | "Perfect Guardian Turtle"
  | "Imperfect Shadow Construct"
  | "Shadow Construct"
  | "Perfect Shadow Construct"
  | "Imperfect Forest Warrior"
  | "Forest Warrior"
  | "Perfect Forest Warrior"
  | "Imperfect Astral Lich"
  | "Astral Lich"
  | "Perfect Astral Lich"
  | "Imperfect Conjuror of Rot"
  | "Conjuror of Rot"
  | "Perfect Conjuror of Rot"
  | "Imperfect Adherent of Zarokh"
  | "Adherent of Zarokh"
  | "Perfect Adherent of Zarokh"
  | (string & {})
