export type Wands =
  | "Driftwood Wand"
  | "Goat's Horn"
  | "Somatic Wand"
  | "Quartz Wand"
  | "Calling Wand"
  | "Spiraled Wand"
  | "Sage Wand"
  | "Pagan Wand"
  | "Faun's Horn"
  | "Blasting Wand"
  | "Crystal Wand"
  | "Coiled Wand"
  | "Convening Wand"
  | "Omen Wand"
  | "Heathen Wand"
  | "Demon's Horn"
  | "Kinetic Wand"
  | "Opal Wand"
  | "Tornado Wand"
  | "Prophecy Wand"
  | "Profane Wand"
  | "Convoking Wand"
  | "Assembler Wand"
  | "Congregator Wand"
  | "Accumulator Wand"
  | (string & {})
