export const DIV_CARD_HIDE_LIST = [
  "A Mother's Parting Gift",
  "Alivia's Grace",
  "Audacity",
  "Call to the First Ones",
  "Cartographer's Delight",
  "Cursed Words",
  "Destined to Crumble",
  "Echoes of Love",
  "Forbidden Power",
  "Grave Knowledge",
  "Lantador's Lost Love",
  "Light and Truth",
  "Might is Right",
  "Prosperity",
  "Rain Tempter",
  "Rats",
  "Rebirth",
  "Reckless Ambition",
  "Struck by Lightning",
  "The Adventuring Spirit",
  "The Army of Blood",
  "The Avenger",
  "The Beast",
  "The Betrayal",
  "The Blazing Fire",
  "The Brawny Battle Mage",
  "The Carrion Crow",
  "The Cataclysm",
  "The Catch",
  "The Coming Storm",
  "The Conduit",
  "The Cursed King",
  "The Deceiver",
  "The Deep Ones",
  "The Demoness",
  "The Dreamland",
  "The Drunken Aristocrat",
  "The Fathomless Depths",
  "The Feast",
  "The Fletcher",
  "The Forsaken",
  "The Fox in the Brambles",
  "The Golden Era",
  "The Harvester",
  "The Hermit",
  "The Incantation",
  "The Inoculated",
  "The Insatiable",
  "The Jester",
  "The Journalist",
  "The King's Blade",
  "The Lich",
  "The Lord in Black",
  "The Lord of Celebration",
  "The Lover",
  "The Lunaris Priestess",
  "The Master",
  "The Metalsmith's Gift",
  "The Oath",
  "The Opulent",
  "The Pack Leader",
  "The Poet",
  "The Rabid Rhoa",
  "The Return of the Rat",
  "The Ruthless Ceinture",
  "The Scarred Meadow",
  "The Scavenger",
  "The Sigil",
  "The Siren",
  "The Spoiled Prince",
  "The Sun",
  "The Surgeon",
  "The Sword King's Salute",
  "The Throne",
  "The Twins",
  "The Visionary",
  "The Warden",
  "The Watcher",
  "The Web",
  "The Witch",
  "The Wolf's Shadow",
  "Thirst for Knowledge",
  "Thunderous Skies",
  "Turn the Other Cheek",
  "Vile Power",
  "Her Mask",
  "Man With Bear",
  "The Card Sharp",
  "The Journey",
  "Rain of Chaos",
  "The Flora's Gift",
  "The Gambler",
  "The Deal",
  "Buried Treasure",
  "The Skeleton",
  "Anarchy's Price",
  "The Traitor",
  "Hunter's Resolve",
  "Atziri's Arsenal",
  "Mitts",
  "The Gladiator",
  "The Puzzle",
  "The Summoner",
  "The Explorer",
  "Lysah's Respite",
  "The Tower",
  "Lingering Remnants",
  "Treasure Hunter",
  "The Realm",
  "The Battle Born",
  "The Gentleman",
  "The Wolf's Legacy",
  "Doedre's Madness",
  "The Mercenary",
] as const
