import * as csv from "fast-csv"
import { createReadStream, existsSync, mkdirSync, readdirSync, unlinkSync, writeFileSync } from "fs"
import { join } from "path"
import { format, resolveConfig } from "prettier"

type BaseTypeRow = {
  "Class"?: string
  "BaseType"?: string
  "DropLevel"?: string
  "Rarity"?: string
  "Height"?: string
  "Width"?: string
  "Sockets"?: string
  "Quality"?: string
  "Corrupted"?: string
  "SubGroup A"?: string
  "SubGroup B"?: string
  "SubGroup Tier"?: string
  "Game:Strength"?: string
  "Game:Dexterity"?: string
  "Game:Intelligence"?: string
  "Game:Damage From"?: string
  "Game:Damage To"?: string
  "Game:APS"?: string
  "Game:DPS"?: string
  "Game:Crit"?: string
  "Game:Implicit 1"?: string
  "Game:Implicit 2"?: string
  "Game:Armour"?: string
  "Game:Armour Max"?: string
  "Game:Evasion"?: string
  "Game:Evasion Max"?: string
  "Game:Energy Shield"?: string
  "Game:Energy Shield Max"?: string
  "Game:Block"?: string
}

const AUTOGENERATED_TYPES_DIR = join(__dirname, "../types/autogenerated")
const BASE_TYPES_CSV_PATH = join(__dirname, "../assets/BaseTypes.csv")
const ITEMS_TYPES_PATH = join(__dirname, "../types/items.ts")

const normalizeItemClassName = (itemClass: string) => itemClass.replace(/\s/gim, "")

export async function parseBaseTypes() {
  const baseTypesRaw: BaseTypeRow[] = []
  const itemClasses: Record<string, string[]> = {}

  const writeFormattedFile = async (filePath: string, content: string) => {
    const prettierConfig = await resolveConfig(filePath)
    const formattedContent = await format(content, { ...prettierConfig, filepath: filePath })
    writeFileSync(filePath, formattedContent)
  }

  createReadStream(BASE_TYPES_CSV_PATH)
    .pipe(csv.parse({ headers: true }))
    .on("data", (row) => {
      baseTypesRaw.push(row as BaseTypeRow)
    })
    .on("error", () => console.log("Error wile trying to generate types"))
    .on("end", async () => {
      for (const row of baseTypesRaw) {
        if (!itemClasses[row.Class]) {
          itemClasses[row.Class] = []
        }

        itemClasses[row.Class].push(row.BaseType)
      }

      // Generate path if not already there, delete all files if they exist
      if (!existsSync(AUTOGENERATED_TYPES_DIR)) {
        mkdirSync(AUTOGENERATED_TYPES_DIR)
      } else {
        const files = readdirSync(AUTOGENERATED_TYPES_DIR)
        for (const file of files) {
          unlinkSync(join(AUTOGENERATED_TYPES_DIR, file))
        }
      }

      // Generate item classes typescript type
      const itemClassNames = Object.keys(itemClasses)
      const generatedTypeNames = itemClassNames.map(normalizeItemClassName)
      const itemClassesFile = `export type ItemClasses = ${itemClassNames.map((i) => `"${i}"`).join(" | ")} | (string & {})`

      await writeFormattedFile(join(AUTOGENERATED_TYPES_DIR, "ItemClasses.ts"), itemClassesFile)

      // For each item class, generate a typescript type of the base types in that class
      for (const [itemClass, baseTypes] of Object.entries(itemClasses)) {
        const name = normalizeItemClassName(itemClass)
        const file = `export type ${name} = ${baseTypes.map((i) => `"${i}"`).join(" | ")} | (string & {})`

        await writeFormattedFile(join(AUTOGENERATED_TYPES_DIR, `${name}.ts`), file)
      }

      // Create an index file that exports all of those
      const indexFile =
        "export * from './ItemClasses'\n" +
        itemClassNames.map((itemClass) => `export * from './${normalizeItemClassName(itemClass)}'`).join("\n")

      await writeFormattedFile(join(AUTOGENERATED_TYPES_DIR, "index.ts"), indexFile)

      const itemsFile = `// This file is autogenerated by src/scripts/generateTypes.ts
import {
  ItemClasses,
  ${generatedTypeNames.join(",\n  ")}
} from "./autogenerated"

export type BaseType =
  ${generatedTypeNames.map((typeName) => `| ${typeName}`).join("\n  ")}

export type ItemClass = ItemClasses
`

      await writeFormattedFile(ITEMS_TYPES_PATH, itemsFile)
    })
}

parseBaseTypes()
